
spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://120.26.173.145:3309/springSecurity?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 619619tey
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  redis:
    host: 120.26.173.145
    port: 6379
  rabbitmq:
    host: 120.26.173.145
    username: guest
    password: guest
    virtual-host: /
#    邮件发送配置
  mail:
    username: 1499989399@qq.com
    password: sgaguiozcpybgdjf
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.enable: true
#sgaguiozcpybgdjf

mybatis:
  mapper-locations: classpath*:com/langsin/my_spring_security/dao/mapper/xml/*.xml
  type-aliases-package: com.langsin.my_spring_security.pojo
debug: false
management:
  #actuator端口 如果不配置做默认使用上面8080端口
  server:
    port: 9090
  endpoints:
    web:
      cors:
        allow-credentials: false
      exposure:
        #默认值访问health,info端点  用*可以包含全部端点
        include: '*'
      #修改访问路径 2.0之前默认是/; 2.0默认是/actuator可以通过这个属性值修改
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
server:
  port: 8080
#  tomcat:
#    max-threads: 3



#logging:
#  level:
#    com.langsin.my_spring_security: debug